### ISSUE TITLE
Taskbar shortcut breaks during update

### ISSUE THREAD

**Issue by michael-reuter** [kmccarthy55/NotepadCode#17]
The NotepadCode icon turns to a blank file icon and says "file not found" when the application is updated. It has to be removed and readded.

**Comment by kmccarthy55** [comment]
This is actually something i will not be able to fix as the way the update works it uninstall the actual application and reinstalling it. 

The application I'm using that creates the install feature I'm using a free version and it does not have the update feature available to use.

Once updates are less frequent hopefully this won't be as noticeable.
