### ISSUE TITLE
Text on menu bar doesn't change colors

### ISSUE THREAD

**Issue by michael-reuter** [kmccarthy55/NotepadCode#20]
This makes it impossible to see which option is selected when you click on it and the background changes color.
![image](https://user-images.githubusercontent.com/17342888/62395982-7870d500-b537-11e9-9585-3687ff05b158.png)

**Comment by kmccarthy55** [comment]
As of right now I'm not able to do this with out building a completely custom menubar. So for now i will close this and will come back to this once i have time to look more into build something that can do what is being asked.
