### ISSUE TITLE
Add 'No to all' save option when closing application

### ISSUE THREAD

**Issue by tylerwinkleman** [kmccarthy55/NotepadCode#26]
If you are like me, you have 50 'Tab #' files open. When closing the application, it asks if I want to save each one. I would like to see either (1) a preference to disable the save dialog on application close for "cached" tabs or (2) a 'No to all' option on the save dialog.

**Comment by kmccarthy55** [comment]
A "no to all" option has been added it will be include in version 1.0.10.0
