### ISSUE TITLE
Seeing Unicode characters being added to file

### ISSUE THREAD

**Issue by tylerwinkleman** [kmccarthy55/NotepadCode#31]
NotepadCode appears to be inserting Unicode characters when converting an ANSI file to UTF-8. When the file is opened in another application, the characters do not display properly.

Original:
;record request (
;  1 debug_ind = i2
;  1 obj_array [*] 
;    2 event_id = f8
;)

Saved with NotepadCode:
;record�request (
;  1 debug_ind = i2
;��1 obj_array [*]�
;����2 event_id = f8
;)

**Comment by kmccarthy55** [comment]
What application do you see those values when after it was saved in NotepadCode?

**Comment by kmccarthy55** [comment]
Issue also happens in other text editors.
