### ISSUE TITLE
Default language colors and vertical line options

### ISSUE THREAD

**Issue by michael-reuter** [kmccarthy55/NotepadCode#7]
First impressions are important and most users will want to immediately use the application and customize it later. Adding default colors for these features will allow users to try them without extra work.

**Comment by cdye91** [comment]
Here is what I have
<img width="327" alt="CCL colors" src="https://user-images.githubusercontent.com/12162015/61325743-f82e3e00-a7da-11e9-9a54-31dc6652f0db.PNG">
 found looks pretty good:

**Comment by kmccarthy55** [comment]
I have added default color but vertical line will not be defaulted on. This has been added to version 1.0.10.0
